name: Release to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: git checkout "${GITHUB_REF:11}"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: npm install, build
        run: |
          npm install
          npm run prepare
          npm run build
          npm run run-test
        env:
          CI: true

      - name: npm release
        run: |
          npm run version -- ${GITHUB_REF:10}
          npm run release
        env:
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_PASS: ${{ secrets.NPM_PASS }}
          CI: true
